spring:
  rabbitmq:
    host: 192.168.23.133
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者的数量
        concurrency: 10
        max-concurrency: 10
        #限制消费者每次只能处理一条消息 处理完再处理下一条消息
        prefetch: 1
        #启动时是否默认启动容器
        auto-startup: true
        default-requeue-rejected: true
    template:

      #关于重试策略
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 1000ms
        multiplier: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cardgame?useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.23.133
    port: 6379
    database: 0
    connect-timeout: 10000ms
  main:
    allow-circular-references: true

mybatis:
  #    mapper-locations: classpath:mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.springbootmybatis.entity

# 分页插件
pagehelper:
  # 指定数据库
  helper-dialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页
  reasonable: false
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false
  support-methods-arguments: true
  params: count=countSql

