spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cardgame?useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  #    mapper-locations: classpath:mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.springbootmybatis.entity
