spring:
  redis:
    host: 192.168.23.133
    port: 6379
    database: 0
    connect-timeout: 10000ms
  main:
    allow-bean-definition-overriding: true
server:
  port: 8070
#redisson:
#  redis:
#    address: 192.168.23.133